resources:
- ../base

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: rbb6359d/revision-patch.yaml
  target:
    kind: Service
- path: rbb6359d/routing-patch.yaml
  target:
    kind: Service
